dist: xenial

language: go

go:
  - 1.11.x

git:
  depth: 1

install: true

notification:
  email: false

before_script:
 - go get github.com/golangci/golangci-lint/cmd/golangci-lint
 - go get -t -v ./...

script:
 - golangci-lint run
 - go test -v -race ./...
